export default {
  electricGuitars: 'electricGuitars',
  accessories: 'accessories',
  parts: 'parts',
  acousticGuitars: 'acousticGuitars',
  amps: 'amps',
  bassGuitars: 'bassGuitars',
  effectsAndPedals: 'effectsAndPedals',
  proAudio: 'proAudio',
  folkInstruments: 'folkInstruments',
  software: 'software',
  drumsAndPercussion: 'drumsAndPercussion',
  homeAudio: 'homeAudio',
  bandAndOrchestra: 'bandAndOrchestra',
  keyboardsAndSynths: 'keyboardsAndSynths',
  djAndLightingGear: 'djAndLightingGear',
};
